version: 0.2

phases:
  pre_build:
    commands:
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      - sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - sudo apt-get update && sudo apt-get install packer
  build:
    commands:
      - make VPC_ID=$VPC_ID SUBNET_ID=$SUBNET_ID EKS_VERSION=$EKS_VERSION $TARGET_NAME | tee build.log
  post_build:
    commands:
      - NAME=$(tail -n 30 build.log | grep Name | cut -d: -f4 | tr -d '" ')
artifacts:
  files:
    - artifacts.json
  name: eks-${TARGET_NAME}-${EKS_VERSION}-$(date +%Y-%m-%d)