name: cis
on:
  pull_request:
    branches:
      - master
jobs:
  pipelines:
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v1
#      - name: Setup Symfony
#        working-directory: 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - run: |
          sudo apt-get install build-essential unzip
          export VER="1.5.6"
          wget https://releases.hashicorp.com/packer/${VER}/packer_${VER}_linux_amd64.zip
          unzip packer_${VER}_linux_amd64.zip
          mv packer /usr/local/bin
          make build-al2-1.18
