name: cis
on:
  push:
    branches:
      - main
jobs:
  pipelines:
    environment: AUDIT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: ap-south-1
      - run: |
          ami=`aws ec2 describe-images --region ap-south-1  --filters "Name=tag:Type,Values=Custom"  --query "reverse(sort_by(Images, &CreationDate))[:1].ImageId"   --output text`
          aws ec2 modify-image-attribute --region ap-south-1 --image-id $ami  --launch-permission "Add=[{UserId=913108190184, UserId=454518750364}]"
